$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false,
            autoplay:true,
            autoplayTimeout:2000,
        },
        1000:{
            items:5,
            nav:true,
            loop:true
        }
    }
})
